# URL del backend de tu sitio
backend:
  name: git-gateway
  branch: main # O 'master', dependiendo de tu rama principal en GitHub

# Dónde se subirán los archivos multimedia (imágenes del blog)
media_folder: "assets/uploads" # La ruta donde se guardarán las imágenes
public_folder: "/assets/uploads" # La ruta desde la cual se accederá a las imágenes

# Definición de las colecciones de contenido. En este caso, solo una: el blog.
collections:
  - name: "blog" # Nombre interno de la colección
    label: "Publicaciones del Blog" # Nombre que verá el cliente en el panel
    folder: "_posts" # Carpeta donde se guardarán los archivos de cada post
    create: true # Permitir la creación de nuevos posts
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Cómo se nombrará cada archivo (ej. 2025-07-02-mi-post.md)
    fields: # Los campos que tendrá cada post
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha de Publicación", name: "date", widget: "datetime" }
      - { label: "Imagen Destacada", name: "thumbnail", widget: "image", required: false }
      - { label: "Cuerpo del Artículo", name: "body", widget: "markdown" }
