# Backend configuration
backend:
  name: git-gateway
  branch: main

# Media files will be stored in the repo under Anahi contabilidad/assets/uploads
media_folder: "Anahi contabilidad/assets/uploads"
# CORRECCIÓN: Se quita la diagonal inicial para que la ruta sea relativa
public_folder: "assets/uploads"

# This is the collection for your blog posts
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Publicaciones del Blog" # Used in the UI
    folder: "Anahi contabilidad/_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., 2025-07-02-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha de Publicación", name: "date", widget: "datetime"}
      - {label: "Imagen Destacada", name: "thumbnail", widget: "image", required: false}
      - {label: "Cuerpo del Artículo", name: "body", widget: "markdown"}
